package com.example.cat.domain.model

data class BreedsItem(
    val suppressedTail: Int? = null,
    val wikipediaUrl: String? = null,
    val origin: String? = null,
    val description: String? = null,
    val experimental: Int? = null,
    val lifeSpan: String? = null,
    val cfaUrl: String? = null,
    val rare: Int? = null,
    val countryCodes: String? = null,
    val lap: Int? = null,
    val id: String? = null,
    val shortLegs: Int? = null,
    val sheddingLevel: Int? = null,
    val dogFriendly: Int? = null,
    val natural: Int? = null,
    val rex: Int? = null,
    val healthIssues: Int? = null,
    val hairless: Int? = null,
    val weight: Weight? = null,
    val altNames: String? = null,
    val adaptability: Int? = null,
    val vocalisation: Int? = null,
    val intelligence: Int? = null,
    val socialNeeds: Int? = null,
    val countryCode: String? = null,
    val childFriendly: Int? = null,
    val vcahospitalsUrl: String? = null,
    val temperament: String? = null,
    val name: String? = null,
    val vetstreetUrl: String? = null,
    val grooming: Int? = null,
    val hypoallergenic: Int? = null,
    val indoor: Int? = null,
    val energyLevel: Int? = null,
    val strangerFriendly: Int? = null,
    val referenceImageId: String? = null,
    val affectionLevel: Int? = null,
    val catFriendly: Int? = null
)